### ISSUE TITLE
Steering Committee Meeting #23 (Jan 2022)

### ISSUE THREAD

**Issue by Winterstorm-j** [rse-aunz/organisation#38]
# Meeting Details:
**Chair**: Nooriyah Lohani
**Date**:  Tues. 25th January 2022
 
**Time**: [event timeanddate.com](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Steering+Committee+Meeting+%2321&iso=20211123T14&p1=152&ah=1)

* Auckland, New Zealand: 4:00 pm (NZDT)
* Brisbane, Australia: 1:00 pm (AEST)
* Melbourne, Australia: 2:00 pm {AEDT)
* Perth, Australia: 11:00 am (AWST)

**Meeting link**: [Join Zoom Meeting](https://nesi.zoom.us/j/88635462552?pwd=QUt2S0x5ZENOSEZtRENvSUl2Y1RnQT09)

# Proposed Agenda:
### 2. Planning Activities
Confirmation of International RSE council rep (RM)
RSE Survey outcome (MS)
Direction/Strategy for the new committee (RM)
Social Media guidelines (RL)
au-RSE conference ideas (RM)

### 4. Any Other Business
* Proposed next meeting: TBA

**Comment by manodeep** [comment]
Agenda item: 
- Domain registration (MS, Done)
- Email aliases for domain (MS, Pending)

**Comment by manodeep** [comment]
Previous email aliases do not work now (e.g.,  steering.committee@rse-aunz)

**Comment by manodeep** [comment]
- Talk at eResearchNZ

**Comment by manodeep** [comment]
Had borked the domain - have finally setup an auto-forward to our github website from the domain

**Comment by rowlandm** [comment]
I did start to look at strategy.

I went through all the minutes since 2019 and tried to identify the recurring tasks of the steering commitee:

International Survey
eResearch AU events
eResearch NZ events
RSE NZ 
C3DIS events
International Council RSE representation
International conference RSE events
Elections for steering committee
Partnership with ARDC
Providing feedback on behalf of the community
Looking at opportunities for the community
Sharing info with the community

That's a lot of responsibility.

Will add more stuff when I can.
